-- =============================================================================
-- PocketSmart AI — Supabase PostgreSQL schema
-- =============================================================================
-- How to run:  Supabase Dashboard -> SQL Editor -> New query -> paste this whole
-- file -> Run.  The script is idempotent: running it again is safe.
--
-- It mirrors backend/database.py exactly (same tables, columns, types, keys and
-- indexes), so the FastAPI backend works against it with no code differences.
--
-- Design notes
--   * The app has its own authentication (bcrypt + JWT, table "users"); it does
--     NOT use Supabase Auth.  All reads/writes go through the FastAPI backend,
--     which connects with the Postgres connection string (DATABASE_URL).
--   * That connection uses the "postgres" role, which bypasses Row Level
--     Security, so RLS never blocks the backend.
--   * Supabase exposes every table in the "public" schema through its REST API
--     to anyone holding the publishable (anon) key.  "users" holds password
--     hashes, so RLS is switched on for every table and the API roles
--     (anon, authenticated) get no access at all.  Only the backend can read
--     or write data.
--   * Timestamps are stored as ISO-8601 text on purpose: the application
--     compares and parses them as strings, and keeping that representation
--     means zero business-logic changes.
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- 1. users
-- -----------------------------------------------------------------------------
create table if not exists public.users (
    id               integer generated by default as identity primary key,
    username         varchar(64)  not null,
    email            varchar(254),
    full_name        varchar(120),
    hashed_password  varchar(255) not null,
    disabled         boolean      not null default false,
    created_at       varchar(40)  not null,
    constraint users_username_not_blank check (length(trim(username)) > 0)
);

-- Case-insensitive uniqueness (the app looks users up with lower(username)).
-- Several rows may have a NULL email; non-NULL emails must be unique.
create unique index if not exists uq_users_username_lower on public.users (lower(username));
create unique index if not exists uq_users_email_lower    on public.users (lower(email));

-- -----------------------------------------------------------------------------
-- 2. recommendations  (one saved plan per row, owned by a user)
-- -----------------------------------------------------------------------------
create table if not exists public.recommendations (
    id           varchar(36)      primary key,            -- uuid4 string generated by the app
    user_id      integer          not null
                 references public.users (id) on delete cascade,
    category     varchar(20)      not null,
    budget       double precision not null,
    preferences  text             not null,               -- JSON document (as text)
    result       text             not null,               -- JSON document (as text)
    "timestamp"  varchar(40)      not null,
    constraint recommendations_category_check check (category in ('home', 'party', 'jewelry')),
    constraint recommendations_budget_check   check (budget >= 1)
);

-- History page: all plans of one user, newest first.
create index if not exists recommendations_user_time
    on public.recommendations (user_id, "timestamp");

-- -----------------------------------------------------------------------------
-- 3. sessions  (server-side login sessions, keyed by the JWT "jti" claim)
-- -----------------------------------------------------------------------------
create table if not exists public.sessions (
    id             varchar(36) primary key,
    user_id        integer     not null
                   references public.users (id) on delete cascade,
    login_time     varchar(40) not null,
    last_activity  varchar(40) not null,
    expires_at     varchar(40) not null,
    revoked        boolean     not null default false,
    user_data      text        not null default '{}'
);

create index if not exists sessions_user          on public.sessions (user_id);
-- Used by the background cleanup job (deletes expired / idle sessions).
create index if not exists sessions_expires_at    on public.sessions (expires_at);
create index if not exists sessions_last_activity on public.sessions (last_activity);

-- -----------------------------------------------------------------------------
-- 4. Row Level Security
-- -----------------------------------------------------------------------------
alter table public.users           enable row level security;
alter table public.recommendations enable row level security;
alter table public.sessions        enable row level security;

-- Take away every table privilege from the public REST/GraphQL roles ...
revoke all on table public.users, public.recommendations, public.sessions
    from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

-- ... and add explicit deny-all policies as a second layer, so the intent is
-- visible in the dashboard and survives an accidental GRANT later on.
-- (service_role and postgres bypass RLS, so the backend is unaffected.)
drop policy if exists "users: no direct api access"           on public.users;
drop policy if exists "recommendations: no direct api access" on public.recommendations;
drop policy if exists "sessions: no direct api access"        on public.sessions;

create policy "users: no direct api access"
    on public.users for all to anon, authenticated
    using (false) with check (false);

create policy "recommendations: no direct api access"
    on public.recommendations for all to anon, authenticated
    using (false) with check (false);

create policy "sessions: no direct api access"
    on public.sessions for all to anon, authenticated
    using (false) with check (false);

commit;

-- -----------------------------------------------------------------------------
-- Optional verification queries (run separately)
-- -----------------------------------------------------------------------------
-- select tablename, rowsecurity from pg_tables where schemaname = 'public'
--   and tablename in ('users','recommendations','sessions');          -- rowsecurity = true
-- select indexname from pg_indexes where schemaname = 'public' order by 1;
-- select * from pg_policies where schemaname = 'public';
